/**
 * Cathay Pacific Confidential and Proprietary.
 * Copyright 2011, Cathay Pacific Airways Limited
 * All rights reserved.
 *
 */
//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//
package com.cathaypacific.mmbbizrule.cxservice.olci.model;
/**
 * The Enum IndicatorType.
 */
public enum IndicatorType {
    /** The Y. */
    Y,
    /** The N. */
    N;
    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }
    /**
     * From value.
     *
     * @param v the v
     * @return the indicator type
     */
    public static IndicatorType fromValue(final String v) {
        return valueOf(v);
    }
}
